apiVersion: apps/v1
kind: Deployment
metadata:
        name: {{ .Release.Name }}-deployment
spec:
        replicas: {{ .Values.replicaCount }}
        selector:
                matchLabels:
                        app: gateway
        template:
                metadata:
                        labels:
                                app: gateway
                spec:
                        containers:
                                - name: gateway
                                  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
                                  ports:                                        
                                        - containerPort: 8001
                                  env:
                                        - name: USERS_SERVICE_URL
                                          value: {{ .Values.users_service_url }}
                                        - name: ORDERS_SERVICE_URL
                                          value: {{ .Values.users_service_url }}
