apiVersion: v1
kind: Service
metadata:
        name: {{ .Release.Name }}-service
spec:
        selector:
                app: gateway
        type: NodePort
        ports:
                - protocol: TCP
                  port: 8001
                  targetPort: 8000
                  nodePort: {{ .Values.nodePort }} 
